version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "stats:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  producer:
    image: peterc/jbhh-producer-example:latest
    build:
      context: ./producer
    ports:
      - "8282:80"

  consumer:
    image: peterc/jbhh-consumer-example:latest
    build:
      context: ./consumer
    ports:
      - "8283:80"
